-- 1. Profiles Table
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text unique not null,
  full_name text,
  company_name text,
  provider text default 'email',
  tenant_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;
create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

-- 2. Tenant Configurations Table
create table public.tenant_configurations (
  id bigint generated by default as identity primary key,
  tenant_id text unique not null,
  max_rules integer default 5,
  row_scan_depth integer default 500,
  is_premium boolean default false,
  trial_expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tenant_configurations enable row level security;
create policy "Users can view their tenant config" on public.tenant_configurations for select using (
  tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- 3. Tenant Quad-Store Table
create table public.tenant_quad_store (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  subject text not null,
  predicate text not null,
  object_val text not null,
  rule_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index idx_quad_store_tenant on public.tenant_quad_store(tenant_id);

alter table public.tenant_quad_store enable row level security;
create policy "Users can view their tenant quads" on public.tenant_quad_store for select using (
  tenant_id in (select tenant_id from public.profiles where id = auth.uid())
);

-- 4. Automatic Onboarding Trigger
create or replace function public.handle_new_user() 
returns trigger as $$
declare
  extracted_provider text;
begin
  extracted_provider := new.raw_app_meta_data->>'provider';
  if extracted_provider is null then
    extracted_provider := 'email';
  end if;

  insert into public.profiles (id, email, full_name, provider, tenant_id)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name',
    extracted_provider,
    'tenant_' || new.id
  );
  
  insert into public.tenant_configurations (tenant_id, trial_expires_at)
  values (
    'tenant_' || new.id,
    now() + interval '30 days'
  );
  
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
